### ISSUE TITLE
Implement a command-line flag to shorten URLs

### ISSUE THREAD

**Issue by kronikpillow** [Calinou/0x0#1]
I'm not good at scripting, only 7-8 months in to linux, but I use this script on a regular basis to upload screenshots, I would love to see a function to shorten urls as well in it if possible :))) would remove the need to use services like bitly and similar :))

**Comment by Calinou** [comment]
I'm not sure about this. Implementing this feature is easy, but [URL shorteners have many shortcomings](https://en.wikipedia.org/wiki/URL_shortening#Shortcomings) such as linkrot. They're also becoming less relevant, as more programs/games support copy-pasting and clicking URLs to open them.

**Comment by kronikpillow** [comment]
I find them useful for sharing spreadsheets and long links, I still haven't learned shell scripting :D would love the feature :) c

**Comment by Calinou** [comment]
@kronikpillow Sorry, but I think this is out of scope for this particular script. I'd like to keep this script small, as shell scripts aren't renowned for their ability to scale up :slightly_smiling_face: 

You could find another script to accomplish this task or write one yourself.
